#include "LESDK\Common\Common.hpp"

#include "LESDK\LE2\Core_structs.hpp"
#include "LESDK\LE2\Core_classes.hpp"
#include "LESDK\LE2\Core_f_structs.hpp"
// #include "LESDK\LE2\Core_functions.cpp"
#include "LESDK\LE2\Engine_structs.hpp"
#include "LESDK\LE2\Engine_classes.hpp"
#include "LESDK\LE2\Engine_f_structs.hpp"
// #include "LESDK\LE2\Engine_functions.cpp"
#include "LESDK\LE2\IpDrv_structs.hpp"
#include "LESDK\LE2\IpDrv_classes.hpp"
#include "LESDK\LE2\IpDrv_f_structs.hpp"
// #include "LESDK\LE2\IpDrv_functions.cpp"
#include "LESDK\LE2\GFxUI_structs.hpp"
#include "LESDK\LE2\GFxUI_classes.hpp"
#include "LESDK\LE2\GFxUI_f_structs.hpp"
// #include "LESDK\LE2\GFxUI_functions.cpp"
#include "LESDK\LE2\WwiseAudio_structs.hpp"
#include "LESDK\LE2\WwiseAudio_classes.hpp"
#include "LESDK\LE2\WwiseAudio_f_structs.hpp"
// #include "LESDK\LE2\WwiseAudio_functions.cpp"
#include "LESDK\LE2\WinDrv_structs.hpp"
#include "LESDK\LE2\WinDrv_classes.hpp"
#include "LESDK\LE2\WinDrv_f_structs.hpp"
// #include "LESDK\LE2\WinDrv_functions.cpp"
#include "LESDK\LE2\SFXOnlineFoundation_structs.hpp"
#include "LESDK\LE2\SFXOnlineFoundation_classes.hpp"
#include "LESDK\LE2\SFXOnlineFoundation_f_structs.hpp"
// #include "LESDK\LE2\SFXOnlineFoundation_functions.cpp"
#include "LESDK\LE2\SFXGame_structs.hpp"
#include "LESDK\LE2\SFXGame_classes.hpp"
#include "LESDK\LE2\SFXGame_f_structs.hpp"
// #include "LESDK\LE2\SFXGame_functions.cpp"
#include "LESDK\LE2\PlotManagerMap_structs.hpp"
#include "LESDK\LE2\PlotManagerMap_classes.hpp"
#include "LESDK\LE2\PlotManagerMap_f_structs.hpp"
// #include "LESDK\LE2\PlotManagerMap_functions.cpp"
#include "LESDK\LE2\PlotManager_structs.hpp"
#include "LESDK\LE2\PlotManager_classes.hpp"
#include "LESDK\LE2\PlotManager_f_structs.hpp"
// #include "LESDK\LE2\PlotManager_functions.cpp"
#include "LESDK\LE2\BIOC_Materials_structs.hpp"
#include "LESDK\LE2\BIOC_Materials_classes.hpp"
#include "LESDK\LE2\BIOC_Materials_f_structs.hpp"
// #include "LESDK\LE2\BIOC_Materials_functions.cpp"
#include "LESDK\LE2\SFXGameContent_Bonuses_structs.hpp"
#include "LESDK\LE2\SFXGameContent_Bonuses_classes.hpp"
#include "LESDK\LE2\SFXGameContent_Bonuses_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContent_Bonuses_functions.cpp"
#include "LESDK\LE2\SFXGameContent_Powers_structs.hpp"
#include "LESDK\LE2\SFXGameContent_Powers_classes.hpp"
#include "LESDK\LE2\SFXGameContent_Powers_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContent_Powers_functions.cpp"
#include "LESDK\LE2\SFXGameContent_Inventory_structs.hpp"
#include "LESDK\LE2\SFXGameContent_Inventory_classes.hpp"
#include "LESDK\LE2\SFXGameContent_Inventory_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContent_Inventory_functions.cpp"
#include "LESDK\LE2\SFXGameContent_structs.hpp"
#include "LESDK\LE2\SFXGameContent_classes.hpp"
#include "LESDK\LE2\SFXGameContent_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContent_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_00_Shared_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_00_Shared_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_00_Shared_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_00_Shared_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_UNC_Moment01_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_UNC_Moment01_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_UNC_Moment01_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_UNC_Moment01_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_HEN_VT_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_HEN_VT_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_HEN_VT_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_HEN_VT_functions.cpp"
#include "LESDK\LE2\SFXGameDLC_PRE_Cerberus_structs.hpp"
#include "LESDK\LE2\SFXGameDLC_PRE_Cerberus_classes.hpp"
#include "LESDK\LE2\SFXGameDLC_PRE_Cerberus_f_structs.hpp"
// #include "LESDK\LE2\SFXGameDLC_PRE_Cerberus_functions.cpp"
#include "LESDK\LE2\SFXGameDLC_PRE_Collectors_structs.hpp"
#include "LESDK\LE2\SFXGameDLC_PRE_Collectors_classes.hpp"
#include "LESDK\LE2\SFXGameDLC_PRE_Collectors_f_structs.hpp"
// #include "LESDK\LE2\SFXGameDLC_PRE_Collectors_functions.cpp"
#include "LESDK\LE2\SFXGameContentDLC_PRE_DA_structs.hpp"
#include "LESDK\LE2\SFXGameContentDLC_PRE_DA_classes.hpp"
#include "LESDK\LE2\SFXGameContentDLC_PRE_DA_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContentDLC_PRE_DA_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_PRE_Terminus_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_PRE_Terminus_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_PRE_Terminus_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_PRE_Terminus_functions.cpp"
#include "LESDK\LE2\SFXGameDLC_PRE_Terminus_structs.hpp"
#include "LESDK\LE2\SFXGameDLC_PRE_Terminus_classes.hpp"
#include "LESDK\LE2\SFXGameDLC_PRE_Terminus_f_structs.hpp"
// #include "LESDK\LE2\SFXGameDLC_PRE_Terminus_functions.cpp"
#include "LESDK\LE2\SFXGameDLC_PRE_General_structs.hpp"
#include "LESDK\LE2\SFXGameDLC_PRE_General_classes.hpp"
#include "LESDK\LE2\SFXGameDLC_PRE_General_f_structs.hpp"
// #include "LESDK\LE2\SFXGameDLC_PRE_General_functions.cpp"
#include "LESDK\LE2\SFXGameContentDLC_PRO_Gulp01_structs.hpp"
#include "LESDK\LE2\SFXGameContentDLC_PRO_Gulp01_classes.hpp"
#include "LESDK\LE2\SFXGameContentDLC_PRO_Gulp01_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContentDLC_PRO_Gulp01_functions.cpp"
#include "LESDK\LE2\SFXGameContentDLC_PRO_Pepper01_structs.hpp"
#include "LESDK\LE2\SFXGameContentDLC_PRO_Pepper01_classes.hpp"
#include "LESDK\LE2\SFXGameContentDLC_PRO_Pepper01_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContentDLC_PRO_Pepper01_functions.cpp"
#include "LESDK\LE2\SFXGameContentDLC_PRO_Pepper02_structs.hpp"
#include "LESDK\LE2\SFXGameContentDLC_PRO_Pepper02_classes.hpp"
#include "LESDK\LE2\SFXGameContentDLC_PRO_Pepper02_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContentDLC_PRO_Pepper02_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_UNC_Hammer01_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_UNC_Hammer01_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_UNC_Hammer01_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_UNC_Hammer01_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_HEN_MT_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_HEN_MT_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_HEN_MT_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_HEN_MT_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_CON_Pack01_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_CON_Pack01_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_CON_Pack01_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_CON_Pack01_functions.cpp"
#include "LESDK\LE2\SFXGameContentDLC_MCR_03_structs.hpp"
#include "LESDK\LE2\SFXGameContentDLC_MCR_03_classes.hpp"
#include "LESDK\LE2\SFXGameContentDLC_MCR_03_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContentDLC_MCR_03_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_UNC_Pack01_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_UNC_Pack01_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_UNC_Pack01_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_UNC_Pack01_functions.cpp"
#include "LESDK\LE2\SFXGameContentDLC_UNC_01_AreaMap_structs.hpp"
#include "LESDK\LE2\SFXGameContentDLC_UNC_01_AreaMap_classes.hpp"
#include "LESDK\LE2\SFXGameContentDLC_UNC_01_AreaMap_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContentDLC_UNC_01_AreaMap_functions.cpp"
#include "LESDK\LE2\SFXGameContentDLC_CER_02_structs.hpp"
#include "LESDK\LE2\SFXGameContentDLC_CER_02_classes.hpp"
#include "LESDK\LE2\SFXGameContentDLC_CER_02_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContentDLC_CER_02_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_EXP_Part01_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_EXP_Part01_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_EXP_Part01_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_EXP_Part01_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_DHME1_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_DHME1_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_DHME1_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_DHME1_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_CON_Pack02_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_CON_Pack02_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_CON_Pack02_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_CON_Pack02_functions.cpp"
    //#include "LESDK\LE2\PlotManagerDLC_EXP_Part02_structs.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_EXP_Part02_classes.hpp"
    //#include "LESDK\LE2\PlotManagerDLC_EXP_Part02_f_structs.hpp"
    //// #include "LESDK\LE2\PlotManagerDLC_EXP_Part02_functions.cpp"
#include "LESDK\LE2\SFXGameContentDLC_UPD_Patch02_structs.hpp"
#include "LESDK\LE2\SFXGameContentDLC_UPD_Patch02_classes.hpp"
#include "LESDK\LE2\SFXGameContentDLC_UPD_Patch02_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContentDLC_UPD_Patch02_functions.cpp"
#include "LESDK\LE2\SFXGameContentDLC_UPD_Patch03_structs.hpp"
#include "LESDK\LE2\SFXGameContentDLC_UPD_Patch03_classes.hpp"
#include "LESDK\LE2\SFXGameContentDLC_UPD_Patch03_f_structs.hpp"
// #include "LESDK\LE2\SFXGameContentDLC_UPD_Patch03_functions.cpp"
#include "LESDK\LE2\SFXGamePawns_structs.hpp"
#include "LESDK\LE2\SFXGamePawns_classes.hpp"
#include "LESDK\LE2\SFXGamePawns_f_structs.hpp"
// #include "LESDK\LE2\SFXGamePawns_functions.cpp"


static_assert(sizeof(UObject) == 0x60);

static_assert(sizeof(UState) == 0x130);
static_assert(offsetof(UState, ProbeMask) == 0x00D0);
static_assert(offsetof(UState, IgnoreMask) == 0x00D8);
static_assert(offsetof(UState, StateFlags) == 0x00E0);
static_assert(offsetof(UState, LabelTableOffset) == 0x00E4);
static_assert(offsetof(UState, FuncMap) == 0x00E8);


static_assert(sizeof(UClass) == 0x1F8);
static_assert(offsetof(UClass, ClassFlags) == 0x0130);
static_assert(offsetof(UClass, ClassCastFlags) == 0x0134);
static_assert(offsetof(UClass, ClassUnique) == 0x0138);
static_assert(offsetof(UClass, ClassWithin) == 0x013C);
static_assert(offsetof(UClass, ClassConfigName) == 0x0144);
static_assert(offsetof(UClass, ClassReps) == 0x014C);
static_assert(offsetof(UClass, NetFields) == 0x015C);
static_assert(offsetof(UClass, ClassDefaultObject) == 0x016C);
static_assert(offsetof(UClass, UnknownData174) == 0x0174);
